# import os
# from spotipy import Spotify
# from spotipy.oauth2 import SpotifyOAuth
# from dotenv import load_dotenv

# # Load environment variables from .env file
# load_dotenv()

# SPOTIPY_CLIENT_ID = os.getenv('SPOTIPY_CLIENT_ID')
# SPOTIPY_CLIENT_SECRET = os.getenv('SPOTIPY_CLIENT_SECRET')
# SPOTIPY_REDIRECT_URI = os.getenv('SPOTIPY_REDIRECT_URI')

# scope = 'playlist-modify-public playlist-modify-private'
# sp = Spotify(auth_manager=SpotifyOAuth(scope=scope))

# def create_playlist(user_id, name, description=""):
#     playlist = sp.user_playlist_create(user_id, name, public=True, description=description)
#     return playlist['id']

# def add_tracks_to_playlist(playlist_id, track_ids):
#     sp.playlist_add_items(playlist_id, track_ids)

# def main():
#     # Get the user ID
#     user_id = sp.current_user()['id']

#     # Read track IDs from the file generated by dj_sequencer.py
#     with open('dj_set_track_ids.txt', 'r') as f:
#         track_ids = [line.strip() for line in f.readlines()]

#     # Create a new playlist
#     playlist_name = "Generated DJ Set"
#     playlist_description = "A DJ set generated using a genetic algorithm"
#     playlist_id = create_playlist(user_id, playlist_name, playlist_description)

#     # Add tracks to the playlist
#     add_tracks_to_playlist(playlist_id, track_ids)

#     print(f"Playlist '{playlist_name}' created successfully with {len(track_ids)} tracks.")

# if __name__ == "__main__":
#     main()
